Repository CatDogEngine/AssetPipeline, pull requests merged in 2023-02, with the labels that each got.

#109 Terrain Producer Refactor
  auto/producers/terrain_producer.lua
  examples/GenerateTerrainToCatDog/Main.cpp
  examples/GenerateTerrainToFbx/Main.cpp
  private/Math/MeshGenerator.cpp
  private/Math/NoiseGenerator.cpp
  private/Producers/TerrainProducer/HeightFunctions.cpp
  private/Producers/TerrainProducer/Noise/Noise.h
  private/Producers/TerrainProducer/TerrainProducer.cpp
  private/Producers/TerrainProducer/TerrainProducerImpl.cpp
  private/Producers/TerrainProducer/TerrainProducerImpl.h
  private/Scene/Texture.cpp
  private/Scene/TextureImpl.cpp
  private/Scene/TextureImpl.h
  public/IO/InputArchive.hpp
  public/IO/OutputArchive.hpp
  public/Math/NoiseGenerator.h
  public/Producers/TerrainProducer/HeightFunctions.h
  public/Producers/TerrainProducer/TerrainParameter.h
  public/Producers/TerrainProducer/TerrainProducer.h
  public/Producers/TerrainProducer/TerrainTypes.h
  public/Scene/Texture.h
  public/Scene/TextureFormat.h
  public/Utilities/StringUtils.h
Labels: Terrain, API

#122 Refactor material.
  private/Consumers/CDConsumer/CDConsumerImpl.cpp
  private/Producers/GenericProducer/GenericProducerImpl.cpp
  private/Producers/TerrainProducer/TerrainProducerImpl.cpp
  private/Scene/Material.cpp
  private/Scene/MaterialImpl.cpp
  private/Scene/MaterialImpl.h
  public/PropertyMap/PropertyMap.hpp
  public/Scene/Material.h
  public/Scene/MaterialTextureType.h
Labels: WIP, API

#123 Fix texture serialization bug.
  private/Scene/SceneDatabaseImpl.h
  private/Scene/TextureImpl.h
Labels: LGTM
